apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-api
  template:
    metadata:
      labels:
        app: graphql-api
    spec:
      containers:
        - name: graphql-api
          image: cbdemo2023registry.azurecr.io/graphql-api:v2.3
          ports:
            - name: http
              containerPort: 3040
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "3040"
            - name: PRODUCTS_API_URL
              value: http://products-api-service
            - name: PRICE_API_GRPC_URL
              value: price-api-service:5000
            - name: APPLICATIONINSIGHTS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: cb-demo-secret
                  key: APPLICATIONINSIGHTS_CONNECTION_STRING
                  optional: false
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
