version: "3.9"

services:
  products-api:
    image: ${DOCKER_REGISTRY_AND_PATH}/products-api:v2.3
    build:
      context: ./src/products-api
      dockerfile: Dockerfile
  price-api:
    image: ${DOCKER_REGISTRY_AND_PATH}/price-api:v2
    build:
      context: ./src/price-api
      dockerfile: Dockerfile
  graphql-api:
    image: ${DOCKER_REGISTRY_AND_PATH}/graphql-api:v2.4
    build:
      context: ./src/graphql-api
      dockerfile: Dockerfile
  frontend:
    image: ${DOCKER_REGISTRY_AND_PATH}/frontend:v2.3
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_GRAPHQL_API_URL=/graphql
        - NEXT_PUBLIC_SERVER_GRAPHQL_API_URL=http://graphql-api-service/graphql
        - NEXT_PUBLIC_APPLICATIONINSIGHTS_CONNECTION_STRING=${APPLICATIONINSIGHTS_CONNECTION_STRING}
