version: "3.9"

networks:
  cb-demo-local:
    external: true

services:
  seed-products-db:
    image: mongo
    command: mongoimport --collection products --db products --type json --jsonArray --uri "$MONGO_DB_URI" /products.json
    volumes:
      - ./data/products-db/products.json:/products.json
  seed-price-db:
    build:
      context: ./
      dockerfile: ./data/price-db/seed-app/Dockerfile
    environment:
      - ConnectionStrings__PriceDb=$ConnectionStrings__PriceDb
      - DATA_JSON_PATH=/app/products.json
    volumes:
      - ./data/products-db/products.json:/app/products.json
