version: "3.9"

services:
  products-api:
    image: cbdemo2023registry.azurecr.io/products-api:v1
    build:
      context: ./src/products-api
      dockerfile: Dockerfile
  price-api:
    image: cbdemo2023registry.azurecr.io/price-api:v1
    build:
      context: ./src/price-api
      dockerfile: Dockerfile
  graphql-api:
    image: cbdemo2023registry.azurecr.io/graphql-api:v1
    build:
      context: ./src/graphql-api
      dockerfile: Dockerfile
  frontend:
    image: cbdemo2023registry.azurecr.io/frontend:v1
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_GRAPHQL_API_URL=/graphql
        - NEXT_PUBLIC_SERVER_GRAPHQL_API_URL=http://graphql-api-service/graphql
