version: "3.9"

networks:
  cb-demo-local:
    external: true

services:
  products-db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - default
    hostname: localhost
  sqlserver:
    image: price-api-sqlserver
    build:
      context: ./data/price-db
      dockerfile: Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD
    networks:
      - default
    ports:
      - "1433:1433"
    hostname: localhost
  products-api:
    image: products-api
    build:
      context: ./src/products-api
      dockerfile: Dockerfile
    depends_on:
      - products-db
    networks:
      - default
    environment:
      - PORT=3020
      - MONGO_DB_URL=mongodb://products-db:27017/products
    ports:
      - "3020:3020"
  price-api:
    image: price-api
    build:
      context: ./src/price-api
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
    networks:
      - default
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:3030
      - ConnectionStrings__PriceDb
      - DATA_JSON_PATH=/app/products.json
    ports:
      - "3030:3030"
    volumes:
      - ./data/products-db/products.json:/app/products.json
  graphql-api:
    image: graphql-api
    build:
      context: ./src/graphql-api
      dockerfile: Dockerfile
    depends_on:
      - products-api
      - price-api
    networks:
      - default
    environment:
      - PORT=3040
      - PRODUCTS_API_URL=http://products-api:3020
      - PRICE_API_GRPC_URL=price-api:3030
    ports:
      - "3040:3040"
    hostname: graphql-api
  frontend:
    image: frontend
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_GRAPHQL_API_URL=http://localhost:3080/graphql
        - NEXT_PUBLIC_SERVER_GRAPHQL_API_URL=http://graphql-api:3040/graphql
    depends_on:
      - graphql-api
    networks:
      - default
    environment:
      - PORT=3050
      - NEXT_PUBLIC_SERVER_GRAPHQL_API_URL=http://graphql-api:3040/graphql
  proxy:
    build: proxy/.
    ports:
      - "3080:3080"
