version: "3.9"

networks:
  default:
    name: code-base-2023-demo
    driver: bridge

services:
  products-db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - default
  seed-products-db:
    image: mongo
    command: mongoimport --host products-db --db products --collection products --type json --file /products.json --jsonArray
    depends_on:
      - products-db
    networks:
      - default
    volumes:
      - ./data/products-db/products.json:/products.json
  sqlserver:
    image: price-api-sqlserver
    build:
      context: ./data/price-db
      dockerfile: Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD
    networks:
      - default
    ports:
      - "1433:1433"
    hostname: localhost
  init-sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    command: sh -c "sleep 10 && /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P $MSSQL_SA_PASSWORD -d master -i /dbsetup/CreateDatabase.sql"
    depends_on:
      - sqlserver
    environment:
      - MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD
    networks:
      - default
    volumes:
      - ./data/price-db/dbsetup:/dbsetup
