version: "3.9"

networks:
  cb-demo-local:
    external: true

services:
  products-db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - default
    hostname: localhost
  sqlserver:
    image: price-api-sqlserver
    build:
      context: ./data/price-db
      dockerfile: Dockerfile
    environment:
      - MSSQL_SA_PASSWORD=$MSSQL_SA_PASSWORD
    networks:
      - default
    ports:
      - "1433:1433"
    hostname: localhost
