apiVersion: apps/v1
kind: Deployment
metadata:
  name: price-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: price-api
  template:
    metadata:
      labels:
        app: price-api
    spec:
      containers:
        - name: price-api
          image: ${DOCKER_REGISTRY_AND_PATH}price-api:v1
          ports:
            - name: http
              containerPort: 80
          env:
            - name: ConnectionStrings__PriceDb
              valueFrom:
                secretKeyRef:
                  name: cb-demo-secret
                  key: PriceDbConnectionString
                  optional: false
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
