apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-api
  template:
    metadata:
      labels:
        app: products-api
    spec:
      containers:
        - name: products-api
          image: cbdemo2023registry.azurecr.io/products-api:v1
          ports:
            - name: http
              containerPort: 3020
              protocol: TCP
          env:
            - name: PORT
              value: "3020"
            - name: MONGO_DB_URL
              valueFrom:
                secretKeyRef:
                  name: cb-demo-secret
                  key: MongoDbUrl
                  optional: false
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
